version: '3'
services:
    web:
        container_name: django-docker
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        working_dir: /app
        ports: 
            - "8000:8000"
        volumes: 
            - .:/app
        depends_on: 
            - db
    db:
        container_name: django-docker-db
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: django_docker
            MYSQL_USER: root
            MYSQL_PASSWORD: *******
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./custom:/etc/mysql/conf.d
        ports: 
            - "33306:3306"
